# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: db/development
  pool: 5
  username: hendricius
  password:

production:
  adapter: postgresql
  database: db/production
  pool: 5
  username: hendricius
  password:
